spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      routes:
      - id: spring-cloud-feign1
        uri: lb://spring-cloud-feign1
        predicates:
        - Path=/1/**
        filters:
        - StripPrefix=1

server:
  #服务注册中心端口号
  port: 444

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    serviceUrl:
      #服务注册中心的配置内容，指定服务注册中心的位置
      defaultZone: http://localhost:10001/eureka/,http://localhost:10002/eureka/,http://localhost:10003/eureka/
