spring:
  profiles: eureka-server1
server:
  #服务注册中心端口号
  port: 10001
eureka:
  client:
    serviceUrl:
      #服务注册中心的配置内容，指定服务注册中心的位置
      defaultZone: http://localhost:10002/eureka/,http://localhost:10003/eureka/
---
spring:
  profiles: eureka-server2
server:
  #服务注册中心端口号
  port: 10002
eureka:
  client:
    serviceUrl:
      #服务注册中心的配置内容，指定服务注册中心的位置
      defaultZone: http://localhost:10001/eureka/,http://localhost:10003/eureka/
---
spring:
  profiles: eureka-server3
server:
  #服务注册中心端口号
  port: 10003
eureka:
  client:
    serviceUrl:
      #服务注册中心的配置内容，指定服务注册中心的位置
      defaultZone: http://localhost:10001/eureka/,http://localhost:10002/eureka/
