spring:
  profiles:
server:
  port: 12000
---
spring:
  profiles: feign1_1
server:
  port: 12001
---
spring:
  profiles: feign1_2
server:
  port: 12002
---
spring:
  profiles: feign1_3
server:
  port: 12003
